src/blueprints/home.py
import os
from typing import Any, Generator, NoReturn
from flask import Blueprint, Response, current_app, render_template, session

from src.camera.camera import Camera


home_blueprint = Blueprint("home", __name__)


def gen(camera: Camera) -> Generator[Any | bytes, Any, NoReturn]:
    """Generator func for surveillance camera streaming."""
    yield b"--frame\r\n"
    while True:
        frame = camera.get_frame()
        yield b"Content-Type: image/jpeg\r\n\r\n" + frame + b"\r\n--frame\r\n"


@home_blueprint.route("/")
def index() -> str:
    """Home page route"""

    # get theme from session
    theme = session.get("theme", "light")
    
    return render_template("home.html", theme=theme)


@home_blueprint.route("/video_feed")
def video_feed() -> Response:
    """Surveillance camera streaming route"""

    # get the current detector
    detector = current_app.config["DETECTOR"]

    # create a new instance of a camera with the current detector (start with std camera (0))
    camera = Camera(detector, 0)

    return Response(gen(camera), mimetype="multipart/x-mixed-replace; boundary=frame")

src/blueprints/saved.py
import os
from datetime import timezone

from flask import (
    Blueprint,
    Response,
    render_template,
    session,
    request,
    redirect,
    url_for,
    current_app,
)

from src.db.models import VideoSnippet
from src.db.database import db_session

saved_blueprint = Blueprint("saved", __name__)


@saved_blueprint.route("/saved", methods=["GET"])
def saved() -> str:
    """Saved page route"""

    # get theme from session
    theme = session.get("theme", "light")

    if request.method == "GET":

        # get recordings from db
        recordings = db_session.query(VideoSnippet).order_by(VideoSnippet.created).all()
        return render_template("saved.html", theme=theme, recordings=recordings)

    return render_template("saved.html", theme=theme)


@saved_blueprint.route("/saved/player/<video_id>")
def player(video_id: int) -> str:
    """player page"""

    # get theme from session
    theme = session.get("theme", "light")

    # get recording from db
    video_db = db_session.query(VideoSnippet).where(VideoSnippet.id == video_id).first()

    # get date, time and format  it
    date = video_db.created.date()
    time = video_db.created.time().strftime("%H:%M:%S")

    return render_template(
        "player.html",
        theme=theme,
        video_title=video_db.snippetTitle,
        video_id=video_id,
        description=video_db.description,
        date=date,
        time=time,
    )


@saved_blueprint.route("/saved/player/delete/<video_id>")
def delete_recording(video_id: int) -> Response:
    """delete video"""

    # get theme from session
    theme = session.get("theme", "light")

    # get entry
    entry = db_session.query(VideoSnippet).where(VideoSnippet.id == video_id)
    vid_db = entry.first()
    snippetTitle = vid_db.snippetTitle
    thumbnailTitle = vid_db.thumbnailTitle

    try:
        # delete db entry
        entry.delete()
        db_session.commit()

        # delete file(s)
        os.remove(os.path.join(current_app.static_folder, f"recordings/{snippetTitle}"))
        os.remove(
            os.path.join(current_app.static_folder, f"recordings/{thumbnailTitle}")
        )

    except Exception as e:
        print("Error deleting video: {e}")

    # redirect to saved
    return redirect(url_for("saved.saved"))

src/blueprints/settings.py
import json
import os
from typing import Dict

from flask import (
    Blueprint,
    Response,
    render_template,
    request,
    session,
    redirect,
    current_app,
)
from src.camera.camera import Camera
from src.db.models import EmailRecipient, Labels
from src.detector.coco_names import coco_names
from src.db.database import db_session
from src.detector.detector import YoloWorldDetector, YoloV8NDetector


settings_blueprint = Blueprint("settings", __name__)


def get_empty_labels_dict() -> Dict[str, bool]:
    """Get a label dict with all labels set as False"""
    return {l: False for l in coco_names}


# ml models dict
models_dict = {
    "v8world": {
        "model_name": "yolov8world",
        "dropdown_name": "Yolo V8 World (larger, more accurate)",
    },
    "v8nano": {
        "model_name": "yolov8nano",
        "dropdown_name": "Yolo V8 Nano (smaller, less accurate)",
    },
}


@settings_blueprint.route("/settings", methods=["GET", "POST"])
def settings() -> str | Response:
    """Settings page route"""

    # get theme from session
    theme = session.get("theme", "light")

    if request.method == "GET":

        # get labels from db
        labels_db = db_session.query(Labels).where(Labels.id == 1).all()
        labels_dict = labels_db[0].labelsJson

        # get email recipients from db
        recipients = db_session.query(EmailRecipient).all()

        # get model from config
        selected_model=""
        if isinstance(current_app.config["DETECTOR"], YoloWorldDetector):
            selected_model = "v8world"
        elif isinstance(current_app.config["DETECTOR"], YoloV8NDetector):
            selected_model = "v8nano"

        # render
        return render_template(
            "settings.html",
            theme=theme,
            coco_names=labels_dict,
            recipients=recipients,
            models_dict=models_dict,
            selected_model=selected_model
        )

    elif request.method == "POST":

        # if the objects form was triggered
        if "objects_form" in request.form:

            # get new label values
            new_labels = [l for l in request.form.keys()]

            # set new labels in db
            labels_dict = get_empty_labels_dict()
            for l in new_labels:
                if l in labels_dict:
                    labels_dict[l] = True
            db_session.query(Labels).where(Labels.id == 1).update(
                {"labelsJson": labels_dict}
            )
            db_session.commit()

            # stop camera bg thread so new detector can be used
            Camera.stop()

            # get rid of old detector
            del current_app.config["DETECTOR"]

            # create new detector withe the new labels
            recorder = current_app.config["RECORDER"]
            new_detector = YoloWorldDetector(labels=new_labels, recorder=recorder)
            current_app.config["DETECTOR"] = new_detector

            # restart camera background thread
            Camera.start(new_detector)

        # if the email form was triggered
        elif "emails_form" in request.form:

            # validate form
            new_email = request.form["email"]

            # add to db
            db_session.add(EmailRecipient(email_address=new_email))
            db_session.commit()

        # if the ml model change form was triggered
        elif "models_form" in request.form:

            # get the new selection from the form
            new_selection = request.form["ml_selector"]

            # create new detector with current recorder, if one matches
            new_detector = None
            recorder = current_app.config["RECORDER"]

            if new_selection == "v8nano":
                # switch to nano
                new_detector = YoloV8NDetector(recorder=recorder)

            elif new_selection == "v8world":
                # switch to world
                labels_db = db_session.query(Labels).first()  # get labels from db
                labels_dict = labels_db.labelsJson
                labels = [k for k, v in labels_dict.items() if v]

                new_detector = YoloWorldDetector(labels=labels, recorder=recorder)

            # if there is a new detector, reset the camera
            if new_detector:
                # stop camera bg thread so new detector can be used
                Camera.stop()
                # get rid of old detector
                del current_app.config["DETECTOR"]
                current_app.config["DETECTOR"] = new_detector
                # restart camera background thread
                Camera.start(new_detector)

        # redirect (to re-load)
        return redirect("/settings")

    return render_template(
        "settings.html",
        theme=theme,
        coco_names=get_empty_labels_dict(),
        recipients=[],
        models_dict=models_dict,
    )


@settings_blueprint.route("/settings/delete/<id>")
def settings_delete(id: int) -> Response:
    """Delete a specified video then reroute to saved."""

    # delete the record with the passed id
    db_session.query(EmailRecipient).where(EmailRecipient.id == id).delete()
    db_session.commit()

    # redirect to settings
    return redirect("/settings")

src/templates/base.html
<!doctype html>
<title>SB Surveillance - {% block title %}{% endblock %}</title>

<!-- pico css -->
<link rel='stylesheet' href='https://cdn.jsdelivr.net/npm/@picocss/pico@2/css/pico.sand.min.css' />
<link rel='stylesheet' href='https://cdn.jsdelivr.net/npm/@picocss/pico@2/css/pico.colors.min.css' />
<!-- phosphor icons -->
<script src="https://unpkg.com/@phosphor-icons/web"></script>

<link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">


<body>
  <!-- nav bar -->
  <nav>
    <ul>
      <li><strong>SB Surveillance</strong></li>
    </ul>
    <ul>
      <li><a href="{{ url_for('home.index') }}">Home</a></li>
      <li><a href="{{ url_for('saved.saved') }}">Saved</a></li>
      <li><a href="{{ url_for('settings.settings') }}">Settings</a></li>
      <li><a id="themeSwitch"><i id="themeSwitchIcon" class="ph ph-sun"></i></a></li>
    </ul>
  </nav>

  {% block content %}{% endblock %}

  <script>
    const themeBtn = document.getElementById('themeSwitch');
    const themeBtnIcon = document.getElementById('themeSwitchIcon');

    const setToggleButton = (newTheme) => {
      if (newTheme === "light") {
        themeBtnIcon.classList.remove("ph-sun");
        themeBtnIcon.classList.add("ph-moon");
      } else {
        themeBtnIcon.classList.remove("ph-moon");
        themeBtnIcon.classList.add("ph-sun");
      }
    }

    themeBtn.addEventListener("click", (e) => {
      fetch('/toggletheme', { method: 'POST' })
        .then(async (req) => {
          req.json().then((jsonVal) => {
            const newTheme = jsonVal.newTheme;
            document.documentElement.setAttribute('data-theme', newTheme);
            console.log(newTheme)
            setToggleButton(newTheme);
          })
        });
    })

    // On page load, apply the theme passed from Flask
    document.addEventListener("DOMContentLoaded", () => {
      document.documentElement.setAttribute('data-theme', "{{ theme }}");
      setToggleButton("{{ theme }}")
    })

  </script>
</body>

src/templates/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
<div class="container">
  <header>
    <h1>Home</h1>
  </header>
  <main>
    <!-- live stream section -->
    <article class="centered-article">
      <h3>Live Stream</h3>

      <div id="loading-indicator" class="loading-spinner">
        <div aria-busy="true"></div>
      </div>

      <img id="camera-feed" src="{{ url_for('home.video_feed') }}" style="display: none;">
    </article>

    <!-- servo control section -->
    <article class="centered-article">
      <h3>Camera control</h3>
      <button class="move control-btn" id='up'>
        <i class="ph ph-arrow-up"></i>
      </button>

      <div style="display: flex; flex-direction: row;">
        <button class="move control-btn" id='left'>
          <i class="ph ph-arrow-left"></i>
        </button>
        <button class="move control-btn" id='home'>
          <i class="ph ph-house"></i>
        </button>
        <button class="move control-btn" id='right'>
          <i class="ph ph-arrow-right"></i>
        </button>
      </div>
      <button class="move control-btn" id='down'><i class="ph ph-arrow-down"></i></button>
    </article>
  </main>
</div>

<script>

  const camFeed = document.getElementById('camera-feed');
  const loadingIndicator = document.getElementById('loading-indicator');

  camFeed.onload = function () {

    // Hide the loading spinner and show the image
    loadingIndicator.style.display = 'none';
    camFeed.style.display = 'block';
  }

  const moveButtons = document.querySelectorAll(".move");
  moveButtons.forEach(btn => {
    btn.addEventListener('click', (e) => {
      e.preventDefault();
      fetch(`/${btn.id}`)
    })
  })
</script>
{% endblock %}

src/templates/page_not_found.html
{% extends 'base.html' %}

{% block title %}Page Not Found{% endblock %}

{% block content %}
<div class="container">
  <header>
    <h1>Page Not Found</h1>
  </header>
  <main>
    <p>There has been a error! Unfortunately the page you requested was not found. Did you type it in correctly?</p>
  </main>
</div>
{% endblock %}

src/templates/player.html
{% extends 'base.html' %}

{% block title %}Player{% endblock %}

{% block content %}
<div class="container">

  <main>
    <header>
      <h1>Recording Player</h1>
    </header>

    <article class="centered-article">
      <video controls>
        <source src="{{ url_for('static', filename='recordings/' + video_title) }}" type="video/mp4">
        Your browser does not support the video tag.
      </video>
      <table style="margin: 16px;">
        <tbody>
          <tr>
            <td>Title:</td>
            <td>{{ video_title }}</td>
          </tr>
          <tr>
            <td>Date:</td>
            <td>{{ date }}</td>
          </tr>
          <tr>
            <td>Time:</td>
            <td>{{ time }}</td>
          </tr>
          <tr>
            <td>Comments:</td>
            <td>{{ description }}</td>
          </tr>
        </tbody>
      </table>
      <a
        href="{{ url_for('saved.delete_recording', video_id=video_id) }}"><button>delete</button></a>
    </article>
  </main>
</div>
{% endblock %}

src/templates/saved.html
{% extends 'base.html' %}

{% block title %}Saved{% endblock %}

{% block content %}
<div class="container">

  <main>
    <header>
      <h1>Saved</h1>
    </header>

    <h3>Saved movement detection recordings</h3>

    <div class="recordings">
      <!-- iterate recordings -->
      {% for r in recordings %}
      <a href="/saved/player/{{ r.id }}">
        <article class="recording centered-article">
          <img src="{{ url_for('static', filename='recordings/' + r.thumbnailTitle) }}" />
          <p class="recording-text">{{ r.snippetTitle }}</p>
        </article>
      </a>
      {% endfor %}
    </div>
  </main>
</div>
{% endblock %}

src/templates/settings.html
{% extends 'base.html' %}

{% block title %}Settings{% endblock %}

{% block content %}
<div class="container">
    <header>
        <h1>Settings</h1>
    </header>

    <!-- section with email addresses to notify when movement detected -->
    <article class="centered-article">
        <h3>Emails to notify</h3>
        <p>Add emails below that should be notified on detection of movement</p>
        <form method="POST" action="{{ url_for('settings.settings') }}">
            <fieldset role="group">
                <input type="email" name="email" placeholder="Enter the email" autocomplete="email" />
                <input type="submit" value="Add email" name="emails_form" />
            </fieldset>
        </form>
        <ul>
            {% for r in recipients %}
            <li class="no-bullet">
                {{ r.emailAddress }}
                <a class="delete-button" href="{{ url_for('settings.settings_delete', id=r.id) }}"><i id="{{ r.id }}"
                        class="ph ph-x"></i></a>
            </li>
            {% endfor %}
        </ul>
    </article>

    <!-- section with form for models to choose -->
    <article class="centered-article">
        <h3>Models to choose</h3>
        <p>Select your surveillance machine learning model from below:</p>
        <form method="POST" action="{{ url_for('settings.settings') }}">
            <select name="ml_selector" aria-label="Select your ml model..." required>
                <option {% if k == selected_model %} selected {% endif %} disabled value="">
                    Select your model...
                </option>
                {% for k, v in models_dict.items() %}
                <option {% if k == selected_model %} selected {% endif %} value={{k}}>{{v['dropdown_name']}}</option>
                {% endfor %}
            </select>
            <br />
            <button type="submit" name="models_form">Update</button>
        </form>
    </article>

    <!-- section with form for checklist of labels to detect -->
    <article class="centered-article">
        <h3>Objects to detect</h3>
        <p>Select from the list of elements below, what objects should be observed by the surveillance system for
            movement detection</p>
        <form method="POST" action="{{ url_for('settings.settings') }}">
            <div class="objects">
                {% for k, v in coco_names.items() %}
                <div class="object">
                    <input name="{{k}}" type="checkbox" id="{{k}}" {% if v %} checked {% endif %} />
                    <label for="{{k}}">{{k}}</label>
                </div>
                {% endfor %}
            </div>
            <br />
            <button type="submit" name="objects_form">Update</button>
        </form>
    </article>
</div>

<script>

    const modelsFormButton = document.querySelector("button[name='models_form']");
    const objectsFormButton = document.querySelector("button[name='objects_form']");

    const setBusy = (event) => {
        event.target.setAttribute("aria-busy", "true");
    }

    // Add event listeners to the buttons
    modelsFormButton.addEventListener("click", setBusy);
    objectsFormButton.addEventListener("click", setBusy);
</script>

{% endblock %}